name: Generate GitHub page
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
jobs:
  check-and-publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: explcheck
        run: |
          docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/witiko/expltools/explcheck --porcelain --error-format='%f:%l:%c:%e:%k: %t%n %m' expltools/explcheck/testfiles/* >> errors.txt || true
      - run: cat errors.txt
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go install github.com/reviewdog/errorformat/cmd/errorformat@latest
      - run: |
          errorformat -w jsonl '%f:%l:%c:%e:%k: %t%n %m' < errors.txt > errors.list
      - run: cat errors.list
      - run: jq -s . < errors.list > errors.json
      - run: cat errors.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
              pages/main/package-lock.json

      - run: npm ci
        working-directory: pages/main

      - run: npm ci
        working-directory: pages/file
      - name: Create directories and copy files
        run: |
          set -e

          jq -r '.[].filename' < errors.json | sort -u | while read -r filepath; do
            # Remove leading slash to prevent absolute paths
            dir_path="${filepath#/}"

            mkdir -p $dir_path

            # Extract directory (removing filename from path)
            # dir_path="$(dirname "$dir_path")"

            # Create directory structure
            mkdir -p "publish/$dir_path"

            # Copy index.html to the new directory (rename it to match filename if needed)
            cp pages/file/index.html "$dir_path/index.html"

            dir_levels=$(awk -F'/' '{print NF-1}' <<< "$normalized_path")
            repeat_up=""
            for ((i=0; i<dir_levels; i++)); do
              repeat_up+="../"
            done
            sed -i "s#../node_modules#../${repeat_up}node_modules#" "publish/$dir_path/index.html"

            sed -i "s/e102.lua/$(basename $dir_path)/" "publish/$dir_path/index.html"

            if [[ "$dir_path" == *tex ]]; then
              sed -i "s/'lua'/'latex'/" "publish/$dir_path/index.html"
            fi
          done

      - name: Prepare "publish"
        run: |
          mkdir publish
          mv errors.* publish/
          mv pages/main/index.html publish/
          mkdir publish/node_modules
          # inspired by https://stackoverflow.com/a/52408677/873282
          rsync -avh --include='*/' --include='*min*' --exclude='*' pages/ publish/node_modules/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          force_orphan: true
