name: Generate GitHub page
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  check-and-publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
              pages/main/package-lock.json
              pages/file/package-lock.json
      - run: npm ci
        working-directory: pages/main
      - run: npm ci
        working-directory: pages/file

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go install github.com/reviewdog/errorformat/cmd/errorformat@latest

      - name: explcheck (testfiles)
        run: |
          docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/witiko/expltools/explcheck --porcelain --error-format='%f:%l:%c:%e:%k: %t%n %m' expltools/explcheck/testfiles/*.tex >> errors.txt || true

      - name: Get Docker Image Digest
        id: image_digest
        run: |
          DIGEST=$(docker manifest inspect registry.gitlab.com/islandoftex/images/texlive:latest | grep -m1 'digest' | awk -F '"' '{print $4}')
          echo "digest=$DIGEST" >> $GITHUB_ENV

      - name: Cache TeX Files
        id: cache-tex
        uses: actions/cache@v4
        with:
          path: /tmp/texlive
          key: texlive-${{ env.digest }}

      - name: Extract TeX files from TeX Live
        if: steps.cache-tex.outputs.cache-hit != 'true'
        run: |
          # Create and start the container
          CONTAINER_ID=$(docker create registry.gitlab.com/islandoftex/images/texlive:latest)

          # Find all .tex files
          FILES=$(docker run --rm registry.gitlab.com/islandoftex/images/texlive:latest find /usr/local/texlive -type f \( -name "*.tex" -o -name "*.sty" -o -name "*.cls" -o -name "*.opt" \))

          # Copy each file while preserving structure
          for FILE in $FILES; do
            TARGET_PATH="/tmp/texlive${FILE%/*}"  # Extract directory structure
            mkdir -p "$TARGET_PATH"        # Ensure the target directory exists
            docker cp "$CONTAINER_ID:$FILE" "$TARGET_PATH/"
          done

          # Clean up
          docker rm -f $CONTAINER_ID

      - name: Cache Errors
        id: cache-errors
        uses: actions/cache@v4
        with:
          path: /tmp/errors
          key: errors-${{ env.digest }}

      - name: explcheck (TeX Live) | fresh
        if: steps.cache-errors.outputs.cache-hit != 'true'
        run: |
          set -e

          # Ignore errors
          #  - line too long (s103)
          #  - white space (s204)

          timeout 50m bash -c '
            find /tmp/texlive -type f -exec \
              docker run --rm -v "/tmp/texlive:/tmp/texlive" ghcr.io/witiko/expltools/explcheck \
                --porcelain \
                --ignored-issues=w100,s103,s204,s206 \
                --error-format="%f:%l:%c:%e:%k: %t%n %m" \
                {} + | tee -a errors.txt
          ' || echo "Process terminated after 50 minutes."

          errorformat -w jsonl '%f:%l:%c:%e:%k: %t%n %m' < errors.txt > errors.list

          jq -s . < errors.list > errors.json

          mkdir /tmp/errors
          cp errors.* /tmp/errors/

      - name: explcheck (TeX Live) | cache
        if: steps.cache-errors.outputs.cache-hit == 'true'
        run: cp /tmp/errors/errors.* .

      - name: debug
        run: |
          head errors.*
          tail errors.*

      - name: Create directories and copy files
        run: bash -x scripts/create-dirs-for-files.sh

      - name: Prepare "publish"
        run: |
          mv errors.* publish/
          mv pages/main/index.html publish/
          cp 3rd-party/madoko/styles/lang/latex.json publish/

          mkdir publish/node_modules
          # inspired by https://stackoverflow.com/a/52408677/873282
          rsync -ah --include='*/' --include='*min*' --exclude='*' pages/main/node_modules/ publish/node_modules/
          rsync -ah --include='*/' --include='*min*' --include='*/min/***' --exclude='*' pages/file/node_modules/ publish/node_modules/

          cd publish
          ../scripts/create-index-html.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          force_orphan: true
